feat: new wallet support input password and silent options
FuelLabs/forc-wallet pull request #201
Opened 2024-09-10 11:46 UTC by lispking

2024-09-10 11:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FuelLabs/forc-wallet?pullRequest=201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FuelLabs/forc-wallet?pullRequest=201) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FuelLabs/forc-wallet?pullRequest=201) it.</sub>

2024-09-11 18:00 UTC, sdankel commented on src/new.rs
> +    pub password_non_interactive: Option<String>,
Let's call it `unsafe_password`

2024-09-11 23:04 UTC, sdankel requested changes

2024-09-11 23:04 UTC, sdankel commented on src/new.rs
> +    if !new.silent {
We should use the `tracing` crate to control verbosity.

2024-09-11 23:04 UTC, sdankel commented on src/new.rs
> +    pub unsafe_password: Option<String>,
I don't agree that this should be a command line argument. I think we should support an environment variable, but a CLI argument is too easily leaked.

2025-03-25 02:25 UTC, sdankel commented
Hi @lispking , do you still plan to add support for an environment variable?

2025-03-25 02:28 UTC, lispking commented
> Hi @lispking , do you still plan to add support for an environment variable?

There is no plan anymore.

2025-03-25 03:39 UTC, closed without merging