Add derivation for plain address into forc-wallet
FuelLabs/forc-wallet pull request #99
Opened 2023-03-23 23:59 UTC by crypdoughdoteth

By default, we are given the Bech32 format of the public key from the forc-wallet account command, whereas, for Sway, it is required that we use a plain address in the contract. For the convenience of developers, I rigged up the functionality to derive the plain address directly from the CLI with a unit test that sanity checks the type conversion.

2023-03-24 16:12 UTC, kayagokalp requested changes
Thanks for the pr @crypdoughdoteth 🚀, I left some simple comments after those would be very happy to approve!

A side note: `fmt` checks seems to be failing. Could you run `cargo fmt` and commit the changes to have that step passing?

2023-03-24 16:12 UTC, kayagokalp commented on src/account.rs
> +    let bech = Bech32Address::from_str(&public_key).expect("failed to create Bech32 address from String");
Rather than using an `.expect`, let's try to use `?` so that error propagates to the end user rather than a `panic` with some context.

2023-03-28 21:24 UTC, crypdoughdoteth commented
I think the idea is brilliant! Please let me know what you think of the implementation.

2023-03-29 04:28 UTC, mitchmindtree approved these changes
Love it - sysm!

:shipit:

2023-03-29 06:18 UTC, kayagokalp approved these changes
perfect 💯  thanks a lot!

2023-03-29 06:19 UTC, kayagokalp commented
This closes #98

2023-03-29 06:20 UTC, merged